# ref: https://jupyterbook.org/en/stable/customize/config.html

title: Navigating Change: An Evolutionary Study of Innovation, Competition, and Convergence in Economics
author: Sun Tanomkiattikun
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references3.bib
sphinx:
  config:
    bibtex_reference_style: author_year
  extra_extensions:
    - sphinx_jupyterbook_latex
parse:
  myst_enable_extensions:
    - amsmath
