# ref: https://jupyterbook.org/en/stable/customize/config.html

title: A Heterogeneous-agents Model of Endogeneous Growth with Risk Averse Behavior
author: Sun Tanomkiattikun
execute:
  execute_notebooks: force

bibtex_bibfiles:
  - references2.bib
sphinx:
  config:
    bibtex_reference_style: author_year
  extra_extensions:
    - sphinx_jupyterbook_latex
parse:
  myst_enable_extensions:
    - amsmath
